//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Visual Zen++.rc
//
#define DLG_MAIN                        101
#define MENU_MAIN                       102
#define RICHEDIT_OUTPUT                 1001
#define LISTBOX_SCRIPTS                 1002
#define BUTTON_CLEAR_BLUETOOTH          1003
#define BUTTON_ERASE_MEMORY_SLOTS       1004
#define BUTTON_FACTORY_RESET            1005
#define BUTTON_RESET_DEVICE             1006
#define RADIO_PS4_SPECIALITY            1007
#define RADIO_REMOTE_PLAY               1008
#define COMBO_EMULATOR_OUTPUT_PROTOCOL  1009
#define COMBO_OPERATIONAL_MODE          1010
#define COMBO_REMOTE_SLOT_CHANGE        1011
#define SLIDER_VM                       1012
#define SLIDER_DS4_LIGHTBAR             1013
#define LABEL_EMULATOR_OUTPUT_PROTOCOL  1014
#define LABEL_OPERATIONAL_MODE          1015
#define LABEL_REMOTE_SLOT_CHANGE        1016
#define LABEL_VM_SPEED                  1017
#define LABEL_DS4_LIGHTBAR_BRIGHTNESS   1018
#define GROUP_DEVICE_MANAGER            1019
#define GROUP_SLOTS_MANAGER             1020
#define GROUP_OUTPUT                    1021
#define LABEL_SLOT_1                    1022
#define LABEL_SLOT_2                    1023
#define LABEL_SLOT_3                    1024
#define LABEL_SLOT_4                    1025
#define LABEL_SLOT_5                    1026
#define LABEL_SLOT_6                    1027
#define LABEL_SLOT_7                    1028
#define LABEL_SLOT_8                    1029
#define LABEL_SERIAL_NUMBER             1030
#define LABEL_FIRMWARE_VERSION          1031
#define LABEL_FLASH_MEMORY              1032
#define LABEL_DS4_BRIGHTNESS_VALUE      1033
#define LABEL_VM_SPEED_VALUE            1034
#define MENU_FILE_CLEAR_OUTPUT          40000
#define MENU_FILE_EXIT                  40001
#define MENU_CONNECTION_DISCONNECT      40002
#define MENU_CONNECTION_RECONNECT       40003
#define MENU_DEVICE_MONITOR             40004
#define MENU_DEVICE_SERIAL_NUMBER       40005
#define MENU_DEVICE_CLEAR_BLUETOOTH     40006
#define MENU_DEVICE_ERASE_MEMORY_SLOTS  40007
#define MENU_DEVICE_FACTORY_RESET       40008
#define MENU_DEVICE_RESET               40009
#define MENU_DEVICE_EMULATOR_AUTO       40010
#define MENU_DEVICE_EMULATOR_NINTENDOSWITCH 40011
#define MENU_DEVICE_EMULATOR_PCMOBILE   40012
#define MENU_DEVICE_EMULATOR_PLAYSTATION3 40013
#define MENU_DEVICE_EMULATOR_PLAYSTATION45 40014
#define MENU_DEVICE_EMULATOR_XBOX360    40015
#define MENU_DEVICE_EMULATOR_XBOXONE    40016
#define MENU_DEVICE_OPERATIONAL_WHEEL   40017
#define MENU_DEVICE_OPERATIONAL_STANDARD 40018
#define MENU_DEVICE_OPERATIONAL_TOURNAMENT 40019
#define MENU_DEVICE_REMOTESLOT_DISABLED 40020
#define MENU_DEVICE_REMOTESLOT_LEFTSTICK 40021
#define MENU_DEVICE_REMOTESLOT_SELECT   40022
#define MENU_DEVICE_PS4SPECIALITY       40023
#define MENU_DEVICE_REMOTE_PLAY         40024
#define MENU_PROGRAM_LOAD_AND_RUN       40025
#define MENU_PROGRAM_PROGRAM_DEVICE     40026
#define MENU_PLUGINS_PLUGIN_MANAGER		40027
#define MENU_ABOUT_SUPPORT				40028
#define MENU_ABOUT_ABOUT				40029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40065
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
